### PR TITLE
Translation/french

### LINKED ISSUE #15: Translation: French
Hi, I'm toying with the idea to translate this mod to French. What will it take to fully translate all strings to French? Looking for pointers.

Disclosure: I'm a native French speaker and fluent in English.

### PR DESCRIPTION
**Pull request by karthanistyr**
This is a work in progress for a French translation for the various vane modules.
Language code in files is `fr_fr`.
Language code to use in vane module config files is `fr-fr` for consistency and so as to not throw shade to possible future french translation (the minecraft client already has 2 french varieties as per https://minecraft.fandom.com/wiki/Language).

Fix #15 

I'll play-test it for a little while before asking for a merge. I plan on launching my server when paper 1.17.0 has gone through a few bugfix rounds.

### CODE REVIEW

**Review by oddlama — APPROVED** [review]
Obviously I don't understand everything you translated, but from a syntactic viewpoint everything looks sound. Thanks for putting in the work! Please tell me when you are satisfied with the translation and I will merge it.

**Review by yo1frenchtoast — APPROVED** [review]

**Comment by karthanistyr** [comment]
I've updated the inclusive writing for a concise forms, so as not to spill outside of windows in various ingame GUI widgets.
I'm happy for it to be merged at this point.

@yo1frenchtoast if you wish to proof read (or ask others to proof read), you are most welcome.

**Comment by karthanistyr** [comment]
Sorry I missed the train for your 1.17 update btw...

**Comment by karthanistyr** [comment]
Ah but since then there has been a new message in vane core. I'll include it soon.

**Review by yo1frenchtoast — APPROVED** [review]

**Comment by karthanistyr** [comment]
@oddlama ready when you are

**Review by yo1frenchtoast — APPROVED** [review]

**Comment by karthanistyr** [comment]
And thanks to @yo1frenchtoast for checking and validating !

**Review by oddlama — COMMENTED** [review]
Looks great, thanks for your great effort and time! ❤️

**Pull request merged**
